name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.tag_name }}

      - name: Verify tag signature
        run: |
          gpg --import ${{ secrets.DEVELOPER_KEY }}
          git verify-tag ${{ github.event.tag_name }}
          echo "Tag verified successfully"

      - name: Log into the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          cache-from: type=ghcr.io,ref=${{ github.actor }}/${{ github.event.repository.name }}:buildcache
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.tag_name }}
