BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "codes" (
	"user_id"	INTEGER NOT NULL,
	"code"	TEXT NOT NULL,
	"timestamp"	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "user" (
	"id"	INTEGER,
	"username"	TEXT NOT NULL UNIQUE,
	"password"	TEXT NOT NULL,
	"email"	TEXT NOT NULL,
	"level"	INTEGER DEFAULT 0,
	"active"	INTEGER DEFAULT 0,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
