name: Docker Image CI

on:
  push:
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Verify tag signature
        run: |
          echo "${{ secrets.DEVELOPER_KEY }}" | base64 --decode > dev-public-key.gpg
          gpg -q --import dev-public-key.gpg
          (echo 5; echo y; echo save) |
            gpg --command-fd 0 --no-tty --no-greeting -q --edit-key "$(
            gpg --list-packets < dev-public-key.gpg |
            awk '$1=="keyid:"{print$2;exit}')" trust
          git verify-tag "${{ github.ref_name }}"
          rm -f dev-public-key.gpg

      - name: Log into the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          cache-from: type=${{ env.REGISTRY }},ref=${{ github.actor }}/${{ github.event.repository.name }}:buildcache
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
